export function SeededReplayBanner() {
  return (
    <section className="panel" role="note" aria-label="Deterministic seeded replay notice">
      <div className="panelHeader">
        <span className="readOnlyBadge">DETERMINISTIC SEEDED REPLAY</span>
      </div>
      <p>
        This incident contains sanitized competition data generated by{' '}
        <code>scripts/demo-reset.mjs</code>. GitHub publication and GPT-5.6 records are seeded
        replay evidence, not live provider execution.
      </p>
    </section>
  );
}
