import { createHash } from 'node:crypto';
import type { ApprovedRecoveryPackage } from './types.js';

export function buildPullRequestBody(
  input: ApprovedRecoveryPackage,
  sections: {
    rootCause: string;
    changedFiles: string[];
    verificationSummary: string;
    securitySummary: string;
    limitations: string[];
    rollback: string;
  },
): { body: string; digest: string } {
  const body = [
    `# ${input.pullRequestTitle}`,
    '',
    '## Recovery provenance',
    `- Incident: \`${input.incidentId}\``,
    `- Recovery: \`${input.recoveryId}\``,
    `- Treatment plan: \`${input.treatmentPlanId}\``,
    `- Patch version: \`${input.patchVersion}\``,
    `- Base commit: \`${input.baseCommitSha}\``,
    `- Patch digest: \`${input.patchDigest}\``,
    '',
    '## Root cause',
    sections.rootCause,
    '',
    '## Changed files',
    ...sections.changedFiles.map((file) => `- \`${file}\``),
    '',
    '## Security review',
    sections.securitySummary,
    '',
    '## Verification',
    sections.verificationSummary,
    '',
    '## Known limitations',
    ...(sections.limitations.length
      ? sections.limitations.map((item) => `- ${item}`)
      : ['- None recorded.']),
    '',
    '## Rollback',
    sections.rollback,
    '',
    '> Generated by CodeER from an approved, independently verified recovery package. Human review and merge remain required.',
  ].join('\n');
  return { body, digest: createHash('sha256').update(body).digest('hex') };
}
